export const LOGGED_IN = "LOGGED_IN";
export const LOGOUT = "LOGOUT";
export const SETUP_PROFILE = "SETUP_PROFILE";
export const SETUP_INITIAL_PROFILE = "SETUP_INITIAL_PROFILE";
export const SET_MODAL_STATE = "SET_MODAL_STATE";
export const CLOSE_MODAL = "CLOSE_MODAL";
export const SET_STATIC_MODAL = "SET_STATIC_MODAL";
export const SET_CREATE_PROJECT_DIALOG = "SET_CREATE_PROJECT_DIALOG";
